// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmvoHYMESFpHqVrwFleN1I9jKsLveJAf4',
    appId: '1:823537100827:web:d9b76c2202d3d79b6f70be',
    messagingSenderId: '823537100827',
    projectId: 'wordix-60d59',
    authDomain: 'wordix-60d59.firebaseapp.com',
    storageBucket: 'wordix-60d59.firebasestorage.app',
    measurementId: 'G-H0YPC0W5H7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYAKExMw25SXQIfKiysmN_xBwaXmYk3HQ',
    appId: '1:823537100827:android:877b9422540821126f70be',
    messagingSenderId: '823537100827',
    projectId: 'wordix-60d59',
    storageBucket: 'wordix-60d59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqycmsqISR-Ce_twASqxQXt92ChwfEqCc',
    appId: '1:823537100827:ios:04fbbd8a61cfbf966f70be',
    messagingSenderId: '823537100827',
    projectId: 'wordix-60d59',
    storageBucket: 'wordix-60d59.firebasestorage.app',
    iosBundleId: 'com.example.wordix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqycmsqISR-Ce_twASqxQXt92ChwfEqCc',
    appId: '1:823537100827:ios:04fbbd8a61cfbf966f70be',
    messagingSenderId: '823537100827',
    projectId: 'wordix-60d59',
    storageBucket: 'wordix-60d59.firebasestorage.app',
    iosBundleId: 'com.example.wordix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmvoHYMESFpHqVrwFleN1I9jKsLveJAf4',
    appId: '1:823537100827:web:f179ce5424c066616f70be',
    messagingSenderId: '823537100827',
    projectId: 'wordix-60d59',
    authDomain: 'wordix-60d59.firebaseapp.com',
    storageBucket: 'wordix-60d59.firebasestorage.app',
    measurementId: 'G-VNT4XT6QMG',
  );
}
